name: Deployment
on:
    release:
        types: [published]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Ballerina Build
                uses: ballerina-platform/ballerina-action/@master
                with:
                    args:
                        build -a -c
                    env:
                        JIRA_URL: ${{ secrets.JIRA_URL }}
                        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
                        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
                        ISSUE_KEY: ${{ secrets.ISSUE_KEY }}
                        USER_ID: ${{ secrets.USER_ID }}
                        CUSTOMER_EMAIL: ${{ secrets.CUSTOMER_EMAIL }}
            -   name: Ballerina Push
                uses: ballerina-platform/ballerina-action/@master
                with:
                    args:
                        push -a
                env:
                    BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
